In [1]:
import pandas as pd
import numpy as np
import os

In [ ]:
# 获取当前脚本所在文件夹的绝对路径
current_path = os.getcwd()  # 获取当前工作目录
# 获取上原始数据文件夹的绝对路径
parent_path = os.path.join(current_path, "数据")
file_path = os.path.join(parent_path, "Data_V0.csv")
# 读取数据
Data = pd.read_csv(file_path, low_memory=False)
Data.iloc[:5,3:145]

,所属流,suppressSeg,中包覆盖剂编号,C,SI,MN,P,S,CA,AL,...,平均拉速25to26m,平均拉速26to27m,平均拉速27to28m,平均拉速28to29m,平均拉速29to30m,平均拉速30to31m,平均拉速31to32m,平均拉速32to33m,平均拉速33to34m,平均拉速34to35m
0,2,0,2,0.0596,0.0098,0.1214,0.015,0.0079,0.0556,0.0184,...,1.383685,1.384592,1.383412,1.384595,1.384733,1.384558,1.385935,1.385705,1.384568,1.382688
1,2,0,2,0.0596,0.0098,0.1214,0.015,0.0079,0.0556,0.0184,...,1.385473,1.383685,1.384592,1.383412,1.384595,1.384733,1.384558,1.385935,1.385705,1.384568
2,2,0,2,0.0596,0.0098,0.1214,0.015,0.0079,0.0556,0.0184,...,1.384111,1.385473,1.383685,1.384592,1.383412,1.384595,1.384733,1.384558,1.385935,1.385705
3,2,0,2,0.0596,0.0098,0.1214,0.015,0.0079,0.0556,0.0184,...,1.386202,1.384111,1.385473,1.383685,1.384592,1.383412,1.384595,1.384733,1.384558,1.385935
4,2,0,2,0.0596,0.0098,0.1214,0.015,0.0079,0.0556,0.0184,...,1.384792,1.386202,1.384111,1.385473,1.383685,1.384592,1.383412,1.384595,1.384733,1.384558

In [9]:
Data.iloc[:5,145:150]

   中间裂纹  三角区裂纹  角部裂纹  中心偏析  中心疏松
0   0.0    0.0   0.0   0.5   0.5
1   0.0    0.0   0.0   0.5   0.5
2   0.0    0.0   0.0   0.5   0.5
3   0.0    0.0   0.0   0.5   0.5
4   0.0    0.0   0.0   0.5   0.5

In [12]:
Data_features = Data.iloc[:, 3:145]
Data_labels = Data.iloc[:, 145:150]
Data_labels.iloc[:, -1] = Data_labels.iloc[:, -1].clip(
     upper=2.5
)  # 将中心疏松的标签值限制在2.5以下

### 统计5个标签情况

In [ ]:
# 选择要统计的多列数据
selected_columns = Data_labels.iloc[:,:]

# 初始化一个字典来存储每列每个类别的数量
class_counts = {}

# 针对每一列进行统计
for col_idx in range(selected_columns.shape[1]):
    col_data = selected_columns.iloc[:, col_idx]
    unique_classes, counts = np.unique(col_data, return_counts=True)
    class_counts[col_idx] = dict(zip(unique_classes, counts))

# 打印每个类别在每一列中的数量
for col_idx, counts_dict in class_counts.items():
    print(f"Column {col_idx + 1}:")
    for cls, count in counts_dict.items():
        print(f"  Class {cls}: {count} samples")

### 先去除类型特征和化学元素，进行异常值处理

In [ ]:
features =Data_features.iloc[ :, 19:142]
# 获取所有数据类型为object的列
object_columns = ['所属流','suppressSeg','中包覆盖剂编号','下渣报警状态','结晶器保护渣类型','换水口标记','浸入式水口类型']
# 获取所有除化学元素外的连续数据类型列
num_column = ['大包氩气流量', '大包氩气压力', '中间包内钢水温度', '包盖氩气流量', '包盖氩气压力', '上水口氩气流量', '上水口氩气压力', '塞棒氩气流量', '塞棒氩气压力', '滑板氩气流量', '滑板氩气压力', '结晶器过钢量', 
               '结晶器实际液面', '结晶器液面波动值', '结晶器宽度', '结晶器锥度', '电磁搅拌电流', '电磁搅拌频率', '振动单元实际频率', '振动单元实际振幅', '结晶器冷却水温差左窄', '结晶器冷却水温差右窄', '结晶器冷却水温差内弧',
                 '结晶器冷却水温差外弧', '结晶器冷却水流量左窄', '结晶器冷却水流量右窄', '结晶器冷却水流量内弧', '结晶器冷却水流量外弧', '结晶器拉速变化率', '结晶器最小拉速', '结晶器最大拉速', '拉坯长度', '二冷压缩空气总管压力',
                   '二冷水总管温度', '二冷水总管压力', '一区弧宽面实际水量', '一区窄面实际水量', '二区内外弧中部实际水量', '二区内外弧边部实际水量', '三区内外弧中部实际水量', '三区内外弧边部实际水量', '四区内外弧中部实际水量', 
                   '四区内外弧边部实际水量', '五区内外弧中部实际水量', '五区内外弧边部实际水量', '六区内弧中部实际水量', '六区内弧边部实际水量', '六区外弧中部实际水量', '六区外弧边部实际水量', '七区内弧中部实际水量', '七区内弧边部实际水量', 
                   '七区外弧中部实际水量', '七区外弧边部实际水量', '八区内弧中部实际水量', '八区内弧边部实际水量', '八区外弧中部实际水量', '八区外弧边部实际水量', '九区内弧中部实际水量', '九区内弧边部实际水量', '九区外弧中部实际水量', 
                   '九区外弧边部实际水量', '十区内弧中部实际水量', '十区内弧边部实际水量', '十一区内弧中部实际水量', '十一区内弧边部实际水量', '二三区二冷气中部实际值', '二三区二冷气边部实际值', '四区二冷气中部实际值', '四区二冷气边部实际值',
                     '五区二冷气中部实际值', '五区二冷气边部实际值', '六区二冷气中部实际值', '六区二冷气边部实际值', '七区二冷气中部实际值', '七区二冷气边部实际值', '八区二冷气中部实际值', '八区二冷气边部实际值', '九区二冷气中部实际值',
                       '九区二冷气边部实际值', '十区二冷气实际值', '十一区二冷气实际值', '轻压下起点', '轻压下终点', '轻压下总量', '平均拉速0to1m', '平均拉速1to2m', '平均拉速2to3m', '平均拉速3to4m', '平均拉速4to5m', '平均拉速5to6m', 
                       '平均拉速6to7m', '平均拉速7to8m', '平均拉速8to9m', '平均拉速9to10m', '平均拉速10to11m', '平均拉速11to12m', '平均拉速12to13m', '平均拉速13to14m', '平均拉速14to15m', '平均拉速15to16m', '平均拉速16to17m', 
                       '平均拉速17to18m', '平均拉速18to19m', '平均拉速19to20m', '平均拉速20to21m', '平均拉速21to22m', '平均拉速22to23m', '平均拉速23to24m', '平均拉速24to25m', '平均拉速25to26m', '平均拉速26to27m', '平均拉速27to28m',
                         '平均拉速28to29m', '平均拉速29to30m', '平均拉速30to31m', '平均拉速31to32m', '平均拉速32to33m', '平均拉速33to34m', '平均拉速34to35m']
object_column = ['下渣报警状态','结晶器保护渣类型','换水口标记','浸入式水口类型']
# 创建一个新的DataFrame，剔除object类型的列
num_columns = features[num_column].copy()

In [21]:
# 获取每个特征的离群点数量
outliers_count = {}
for feature in num_columns.columns:
    # 计算离群点的数量
    q1 = num_columns[feature].quantile(0.25)
    q3 = num_columns[feature].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers_count[feature] = len(num_columns[(num_columns[feature] < lower_bound) | (num_columns[feature] > upper_bound)])

# 输出每个特征的离群点数量
for feature, count in outliers_count.items():
    print(f"{feature}: {count} outliers")

大包氩气流量: 0 outliers
大包氩气压力: 0 outliers
中间包内钢水温度: 363 outliers
包盖氩气流量: 41 outliers
包盖氩气压力: 60 outliers
上水口氩气流量: 1133 outliers
上水口氩气压力: 202 outliers
塞棒氩气流量: 700 outliers
塞棒氩气压力: 206 outliers
滑板氩气流量: 876 outliers
滑板氩气压力: 242 outliers
结晶器过钢量: 0 outliers
结晶器实际液面: 7 outliers
结晶器液面波动值: 218 outliers
结晶器宽度: 0 outliers
结晶器锥度: 32 outliers
电磁搅拌电流: 0 outliers
电磁搅拌频率: 1060 outliers
振动单元实际频率: 71 outliers
振动单元实际振幅: 72 outliers
结晶器冷却水温差左窄: 448 outliers
结晶器冷却水温差右窄: 80 outliers
结晶器冷却水温差内弧: 10 outliers
结晶器冷却水温差外弧: 9 outliers
结晶器冷却水流量左窄: 0 outliers
结晶器冷却水流量右窄: 0 outliers
结晶器冷却水流量内弧: 0 outliers
结晶器冷却水流量外弧: 0 outliers
结晶器拉速变化率: 623 outliers
结晶器最小拉速: 88 outliers
结晶器最大拉速: 56 outliers
拉坯长度: 0 outliers
二冷压缩空气总管压力: 47 outliers
二冷水总管温度: 6 outliers
二冷水总管压力: 151 outliers
一区弧宽面实际水量: 118 outliers
一区窄面实际水量: 0 outliers
二区内外弧中部实际水量: 125 outliers
二区内外弧边部实际水量: 0 outliers
三区内外弧中部实际水量: 111 outliers
三区内外弧边部实际水量: 0 outliers
四区内外弧中部实际水量: 156 outliers
四区内外弧边部实际水量: 0 outliers
五区内外弧中部实际水量: 456 outliers
五区内外弧边部实际水量: 0 outliers
六区内弧中部实际水量: 640 outliers
六区内弧边部实际水量: 3 outliers
六区外弧中部实际水量: 642 outliers
六区外弧边部实际水量: 3 outliers
七区内弧中部实际水量: 639 outliers
七区内弧边部实际水量: 3 outliers
七区外弧中部实际水量: 986 outliers
七区外弧边部实际水量: 0 outliers
八区内弧中部实际水量: 677 outliers
八区内弧边部实际水量: 0 outliers
八区外弧中部实际水量: 425 outliers
八区外弧边部实际水量: 0 outliers
九区内弧中部实际水量: 773 outliers
九区内弧边部实际水量: 0 outliers
九区外弧中部实际水量: 1044 outliers
九区外弧边部实际水量: 321 outliers
十区内弧中部实际水量: 986 outliers
十区内弧边部实际水量: 349 outliers
十一区内弧中部实际水量: 829 outliers
十一区内弧边部实际水量: 636 outliers
二三区二冷气中部实际值: 0 outliers
二三区二冷气边部实际值: 0 outliers
四区二冷气中部实际值: 981 outliers
四区二冷气边部实际值: 188 outliers
五区二冷气中部实际值: 0 outliers
五区二冷气边部实际值: 982 outliers
六区二冷气中部实际值: 1214 outliers
六区二冷气边部实际值: 131 outliers
七区二冷气中部实际值: 638 outliers
七区二冷气边部实际值: 263 outliers
八区二冷气中部实际值: 606 outliers
八区二冷气边部实际值: 127 outliers
九区二冷气中部实际值: 369 outliers
九区二冷气边部实际值: 162 outliers
十区二冷气实际值: 138 outliers
十一区二冷气实际值: 1148 outliers
轻压下起点: 0 outliers
轻压下终点: 0 outliers
轻压下总量: 0 outliers
平均拉速0to1m: 71 outliers
平均拉速1to2m: 48 outliers
平均拉速2to3m: 34 outliers
平均拉速3to4m: 25 outliers
平均拉速4to5m: 24 outliers
平均拉速5to6m: 26 outliers
平均拉速6to7m: 26 outliers
平均拉速7to8m: 29 outliers
平均拉速8to9m: 32 outliers
平均拉速9to10m: 35 outliers
平均拉速10to11m: 37 outliers
平均拉速11to12m: 38 outliers
平均拉速12to13m: 38 outliers
平均拉速13to14m: 37 outliers
平均拉速14to15m: 36 outliers
平均拉速15to16m: 33 outliers
平均拉速16to17m: 32 outliers
平均拉速17to18m: 31 outliers
平均拉速18to19m: 29 outliers
平均拉速19to20m: 26 outliers
平均拉速20to21m: 24 outliers
平均拉速21to22m: 23 outliers
平均拉速22to23m: 21 outliers
平均拉速23to24m: 18 outliers
平均拉速24to25m: 15 outliers
平均拉速25to26m: 12 outliers
平均拉速26to27m: 11 outliers
平均拉速27to28m: 10 outliers
平均拉速28to29m: 9 outliers
平均拉速29to30m: 8 outliers
平均拉速30to31m: 9 outliers
平均拉速31to32m: 11 outliers
平均拉速32to33m: 12 outliers
平均拉速33to34m: 15 outliers
平均拉速34to35m: 17 outliers

In [24]:
outliers_count = {}
for feature in num_columns.columns:
    # 计算离群点的数量
    q1 = num_columns[feature].quantile(0.25)
    q3 = num_columns[feature].quantile(0.75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    outliers_count[feature] = len(num_columns[(num_columns[feature] < lower_bound) | (num_columns[feature] > upper_bound)])

# 输出每个特征的离群点数量
for feature, count in outliers_count.items():
    print(f"{feature}: {count} outliers")

大包氩气流量: 0 outliers
大包氩气压力: 0 outliers
中间包内钢水温度: 0 outliers
包盖氩气流量: 0 outliers
包盖氩气压力: 0 outliers
上水口氩气流量: 0 outliers
上水口氩气压力: 0 outliers
塞棒氩气流量: 0 outliers
塞棒氩气压力: 0 outliers
滑板氩气流量: 0 outliers
滑板氩气压力: 0 outliers
结晶器过钢量: 0 outliers
结晶器实际液面: 0 outliers
结晶器液面波动值: 0 outliers
结晶器宽度: 0 outliers
结晶器锥度: 0 outliers
电磁搅拌电流: 0 outliers
电磁搅拌频率: 1060 outliers
振动单元实际频率: 0 outliers
振动单元实际振幅: 0 outliers
结晶器冷却水温差左窄: 0 outliers
结晶器冷却水温差右窄: 0 outliers
结晶器冷却水温差内弧: 0 outliers
结晶器冷却水温差外弧: 0 outliers
结晶器冷却水流量左窄: 0 outliers
结晶器冷却水流量右窄: 0 outliers
结晶器冷却水流量内弧: 0 outliers
结晶器冷却水流量外弧: 0 outliers
结晶器拉速变化率: 0 outliers
结晶器最小拉速: 0 outliers
结晶器最大拉速: 0 outliers
拉坯长度: 0 outliers
二冷压缩空气总管压力: 0 outliers
二冷水总管温度: 0 outliers
二冷水总管压力: 0 outliers
一区弧宽面实际水量: 0 outliers
一区窄面实际水量: 0 outliers
二区内外弧中部实际水量: 0 outliers
二区内外弧边部实际水量: 0 outliers
三区内外弧中部实际水量: 0 outliers
三区内外弧边部实际水量: 0 outliers
四区内外弧中部实际水量: 0 outliers
四区内外弧边部实际水量: 0 outliers
五区内外弧中部实际水量: 0 outliers
五区内外弧边部实际水量: 0 outliers
六区内弧中部实际水量: 0 outliers
六区内弧边部实际水量: 0 outliers
六区外弧中部实际水量: 0 outliers
六区外弧边部实际水量: 0 outliers
七区内弧中部实际水量: 0 outliers
七区内弧边部实际水量: 0 outliers
七区外弧中部实际水量: 0 outliers
七区外弧边部实际水量: 0 outliers
八区内弧中部实际水量: 0 outliers
八区内弧边部实际水量: 0 outliers
八区外弧中部实际水量: 0 outliers
八区外弧边部实际水量: 0 outliers
九区内弧中部实际水量: 0 outliers
九区内弧边部实际水量: 0 outliers
九区外弧中部实际水量: 0 outliers
九区外弧边部实际水量: 0 outliers
十区内弧中部实际水量: 0 outliers
十区内弧边部实际水量: 0 outliers
十一区内弧中部实际水量: 0 outliers
十一区内弧边部实际水量: 0 outliers
二三区二冷气中部实际值: 0 outliers
二三区二冷气边部实际值: 0 outliers
四区二冷气中部实际值: 0 outliers
四区二冷气边部实际值: 0 outliers
五区二冷气中部实际值: 0 outliers
五区二冷气边部实际值: 0 outliers
六区二冷气中部实际值: 0 outliers
六区二冷气边部实际值: 0 outliers
七区二冷气中部实际值: 0 outliers
七区二冷气边部实际值: 0 outliers
八区二冷气中部实际值: 0 outliers
八区二冷气边部实际值: 0 outliers
九区二冷气中部实际值: 0 outliers
九区二冷气边部实际值: 0 outliers
十区二冷气实际值: 0 outliers
十一区二冷气实际值: 0 outliers
轻压下起点: 0 outliers
轻压下终点: 0 outliers
轻压下总量: 0 outliers
平均拉速0to1m: 0 outliers
平均拉速1to2m: 0 outliers
平均拉速2to3m: 0 outliers
平均拉速3to4m: 0 outliers
平均拉速4to5m: 0 outliers
平均拉速5to6m: 0 outliers
平均拉速6to7m: 0 outliers
平均拉速7to8m: 0 outliers
平均拉速8to9m: 0 outliers
平均拉速9to10m: 0 outliers
平均拉速10to11m: 0 outliers
平均拉速11to12m: 0 outliers
平均拉速12to13m: 0 outliers
平均拉速13to14m: 0 outliers
平均拉速14to15m: 0 outliers
平均拉速15to16m: 0 outliers
平均拉速16to17m: 0 outliers
平均拉速17to18m: 0 outliers
平均拉速18to19m: 0 outliers
平均拉速19to20m: 0 outliers
平均拉速20to21m: 0 outliers
平均拉速21to22m: 0 outliers
平均拉速22to23m: 0 outliers
平均拉速23to24m: 0 outliers
平均拉速24to25m: 0 outliers
平均拉速25to26m: 0 outliers
平均拉速26to27m: 0 outliers
平均拉速27to28m: 0 outliers
平均拉速28to29m: 0 outliers
平均拉速29to30m: 0 outliers
平均拉速30to31m: 0 outliers
平均拉速31to32m: 0 outliers
平均拉速32to33m: 0 outliers
平均拉速33to34m: 0 outliers
平均拉速34to35m: 0 outliers

### 查看训练集测试集标签分布情况

In [ ]:
# 获取当前脚本所在文件夹的绝对路径
current_path = os.getcwd()  # 获取当前工作目录
# 获取上原始数据文件夹的绝对路径
parent_path = os.path.join(current_path, "数据")
file_path = os.path.join(parent_path, "test_Data_V1.csv")
# 读取数据
Data = pd.read_csv(file_path, low_memory=False)
Data_labels = Data.iloc[:, 158:163]
# 选择要统计的多列数据
selected_columns = Data_labels.iloc[:,:]

# 初始化一个字典来存储每列每个类别的数量
class_counts = {}

# 针对每一列进行统计
for col_idx in range(selected_columns.shape[1]):
    col_data = selected_columns.iloc[:, col_idx]
    unique_classes, counts = np.unique(col_data, return_counts=True)
    class_counts[col_idx] = dict(zip(unique_classes, counts))

# 打印每个类别在每一列中的数量
for col_idx, counts_dict in class_counts.items():
    print(f"Column {col_idx + 1}:")
    for cls, count in counts_dict.items():
        print(f"  Class {cls}: {count} samples")